# Задание 1

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
y = [45, 55, 50, 59, 65, 35, 75, 80, 50, 60]

In [3]:
# y = k*x + b
# y = k_1*x_1 + k_2*x_2 + ... + b

X = np.array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
              [1, 1, 2, 1, 3, 0, 5, 10, 1, 2]])
X.shape

(2, 10)

In [95]:
n = X.shape[1]
W = np.array([1, 0.5])
W

array([1. , 0.5])

In [96]:
def calc_mse(y, y_pred):
    err = np.mean((y - y_pred)**2)
    return err

In [111]:
def grad_boost(number_of_iterations, alpha):
    W_calced = np.copy(W)
    for iteration in range(number_of_iterations):
        y_pred = np.dot(W_calced, X)
        err = calc_mse(y, y_pred)
        for i in range(W_calced.shape[0]):
            W_calced[i] -= alpha * (1/n * 2 * np.sum(X[i] * (y_pred - y)))
        #if iteration % 100 == 0:
        #    print(iteration, W, err)
    return W_calced, err

In [117]:
grad_boost(1500, 1e-4)

(array([ 9.47923318, 10.75338402]), 811.6638152812785)

In [119]:
grad_boost(10000, 1e-4)

(array([31.64269117,  6.78942579]), 176.62240977239327)

In [120]:
grad_boost(100000, 1e-4)

(array([47.2307986 ,  3.91096251]), 45.93750097169106)

In [121]:
grad_boost(300000, 1e-4)

(array([47.23214286,  3.91071429]), 45.93749999999997)

In [122]:
grad_boost(500000, 1e-4)

(array([47.23214286,  3.91071429]), 45.93749999999997)

##### теперь попробуем уменьшить количество итераций меняя alpha

In [124]:
grad_boost(10000, 1e-3)

(array([47.23080513,  3.91096131]), 45.937500964078644)

In [125]:
grad_boost(10000, 1e-2)

(array([47.23214286,  3.91071429]), 45.9375)

In [126]:
grad_boost(1000, 1e-2)

(array([47.23086913,  3.91094949]), 45.93750089064509)

In [127]:
grad_boost(5000, 1e-2)

(array([47.23214286,  3.91071429]), 45.9375)

In [128]:
grad_boost(2500, 1e-2)

(array([47.23214286,  3.91071429]), 45.937499999999986)

In [130]:
grad_boost(2000, 1e-2)

(array([47.23214282,  3.91071429]), 45.937500000000014)

### количество итераций = 2000; alpha = 1e-2

# Задание 2

In [151]:
# исходная функция с ошибкой
def grad_boost2(number_of_iterations, alpha):
    W_calced = np.copy(W)
    for iteration in range(number_of_iterations):
        y_pred = np.dot(W_calced, X)
        err = calc_mse(y, y_pred)
        W_calced -= (alpha * (1/n * 2 * np.sum(X * (y_pred - y))))
    return W_calced, err

In [152]:
grad_boost2(2000, 1e-2)

(array([11.82211538, 11.32211538]), 737.0918269230771)

In [153]:
# исправленная функция
def grad_boost2(number_of_iterations, alpha):
    W_calced = np.copy(W)
    for iteration in range(number_of_iterations):
        y_pred = np.dot(W_calced, X)
        err = calc_mse(y, y_pred)
        W_calced -= (alpha * (1/n * 2 * np.sum(X[0:] * (y_pred - y))))
    return W_calced, err

In [154]:
grad_boost(2000, 1e-2)

(array([47.23214282,  3.91071429]), 45.937500000000014)